### model
model_name_or_path: /data/models/Meta-Llama-3-8B-Instruct
trust_remote_code: true

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: user_entries_sft_p,user_entries_sft_r,user_entries_sft_c
dataset_dir: dataset_sft
template: llama3
cutoff_len: 4096
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/llama3-8b/lora/sft
logging_steps: 50
save_steps: 50
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 50